services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: lecture_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "token"
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - ./work:/home/jovyan/work
      - ~/my-data:/home/jovyan/work/my-data
      - ~/my-data:/data/my-data
    depends_on:
      - elasticsearch
      - elasticsearch2

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: lecture_elasticsearch
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - http.cors.allow-origin="*"
      - ELASTIC_USERNAME=progettoArchi
      - ELASTIC_PASSWORD=progettoArchi
    ports:
      - "9200:9200"
    volumes:
      - ./elastic-data:/var/lib/elasticsearch/data

  elasticsearch2:
    image: elasticsearch:7.17.0
    container_name: lecture_elasticsearch2
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      - http.cors.allow-origin="*"
      - ELASTIC_USERNAME=progettoArchi
      - ELASTIC_PASSWORD=progettoArchi
    ports:
      - "9201:9200"
    volumes:
      - ./elastic-data2:/var/lib/elasticsearch/data

  kibana:
    image: kibana:7.17.0
    container_name: lecture_kibana
    environment:
      - XPACK_MONITORING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200,http://elasticsearch2:9200
      - ELASTICSEARCH_USERNAME=progettoArchi
      - ELASTIC_PASSWORD=progettoArchi
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - elasticsearch2
  
  st-agent:
    image: sematext/agent:latest
    privileged: true
    environment:
      - INFRA_TOKEN=d317b4df-b7ac-40e4-bd4a-58607294c62c
      - REGION=EU
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /var/run/:/var/run
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys:/host/sys:ro
      - /dev:/hostfs/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
